### ISSUE TITLE
Review 12/16

### ISSUE THREAD

**Issue by devamshri** [ashwinbabu888/AP-CSA-T2#40]
Team Section.
Design Manager tangibles
- [x] [Layout](https://github.com/ashwinbabu888/AP-CSA-T2/blob/master/src/main/resources/templates/layout.html)
- [x] [Front End Feature Screen](https://github.com/ashwinbabu888/AP-CSA-T2/blob/master/src/main/resources/templates/GetOrder.html), [runtime link](https://dnhslunchline.tk/GetOrder)
- [x] [Front End Screen 2](https://github.com/ashwinbabu888/AP-CSA-T2/blob/master/src/main/resources/templates/balance.html), [runtime link](https://dnhslunchline.tk/balance)
- [x] [Front End Screen 3](https://github.com/ashwinbabu888/AP-CSA-T2/blob/master/src/main/resources/templates/order.html), [runtime link](https://dnhslunchline.tk/balance)

Scrum Master tangibles
- [x] GitHub README.  <[time box link](https://github.com/ashwinbabu888/AP-CSA-T2#week-3)>
- [x] GitHub Scrum Board <[tickets in review link](https://github.com/ashwinbabu888/AP-CSA-T2/projects/1)> 
Scrum Board <[post winter break backlog link](https://github.com/ashwinbabu888/AP-CSA-T2/issues/37)>

Technical officer tangibles
- [x] Database with CRUD (https://github.com/ashwinbabu888/AP-CSA-T2/blob/master/src/main/java/com/example/sping_portfolio/controllers/db.java):
- [x] [View](https://github.com/ashwinbabu888/AP-CSA-T2/blob/master/src/main/resources/templates/test_db.html)
- [x] [Control](https://github.com/ashwinbabu888/AP-CSA-T2/blob/master/src/main/java/com/example/sping_portfolio/controllers/db.java)
- [ ] [Model SQL]()
- [ ] [Model JPA]()
Deployment manager tangibles
- [x] [Update procedure:](https://github.com/ashwinbabu888/AP-CSA-T2/wiki/Deployment-Guide)
- [x] [Nginx config](https://github.com/ashwinbabu888/AP-CSA-T2/blob/8ceefc467a1ec9ccf31e0de2a13cb48937ca99d7/ngin.conf)
- [x] [Service config](https://github.com/ashwinbabu888/AP-CSA-T2/blob/5787b56254422fd9971be6d9f8a1a864e4761667/service.conf)

GitHub admin tangibles
- [x] [Commit, pull request procedure](https://github.com/ashwinbabu888/AP-CSA-T2/wiki/Commit-Pull-Request---Branching-Techniques)
Branching procedure [Commit, pull request procedure Branching procedure](https://github.com/ashwinbabu888/AP-CSA-T2/wiki/Branching-Procedure)

**Comment by ashwinbabu888** [comment]
Ashwin's Individual Stuff:

Unit 2 FRQ (java)
Unit 3 FRQ (java)
2014 FRQ
Individual About Us Runtime

**Comment by amanj31** [comment]
### Team Grade from Live Review:
Model SQL: Not functioning, -0.25
Model JPA: Incomplete, -0.5
**Team score:** 4.25/5

### Individual Grades:

- Aman J: 4.25/5 team, 2/2 [FRQ 2&3](https://dnhslunchline.tk/individual/AJain), +2 extra credit [2014 FRQ](https://docs.google.com/document/d/1sSmL1JRvg2_GPPmldVKas2YLID6VYEXaqdgsA-TRkLM/edit)
**Total: 8.25/7**
- Devam S: 
- Varnit G:
- Ashwin B: 
- Eshaan P:
-

**Comment by VarnitGupta24** [comment]
Varnit Individual Stuff:
- [Unit 2 FRQ java file](https://github.com/ashwinbabu888/AP-CSA-T2/blob/a74a33edf040f2add190a2184748081e3e695e8b/src/main/java/com/example/sping_portfolio/controllers/IndividualPages.java#L89-L109)
- [Unit 3 FRQ java file](https://github.com/ashwinbabu888/AP-CSA-T2/blob/18a5bfef44da7c2ee8f3f1c85eba4c0529dfb7c9/src/main/java/com/example/sping_portfolio/controllers/IndividualPages.java#L259-L314)
- [2014 FRQ](https://docs.google.com/document/d/1SvM4sASp3QEcXCkKJMp4Vrc_5Veqzw5XIRx4hfOr-Fo/edit)
- [Individual About Us Runtime](https://dnhslunchline.tk/individual/VGupta)

### Team Grade from Live Review:
Model SQL: Not functioning, -0.25
Model JPA: Incomplete, -0.5
**Team score:** 4.25/5

### Individual Grades:

- Varnit G: 4.25/5 team, 2/2 [FRQ 2&3](https://dnhslunchline.tk/individual/VGupta), +2 extra credit [2014 FRQ](https://docs.google.com/document/d/1SvM4sASp3QEcXCkKJMp4Vrc_5Veqzw5XIRx4hfOr-Fo/edit)
**Total: 8.25/7**

**Comment by jm1021** [comment]
The FRQ work has a Class, not sure why you all attempted to build if statements.  Understanding a class would have you build and instance of the class and use setters and getters.  Additionally, you are not yet doing front end to back end input.   This is 1.5/2 at best.  Team score ideas on screen are also lacking, a calculator on a screen does not represent an idea.  The Pizza purchase is a good representation.  Your team seems to have capability, you now need to get some better ideas together and better Java usage models.  7.5/7 seems a more reasonable score, but great week.

**Comment by jm1021** [comment]
Eshan will only get team points.
