### ISSUE TITLE
Devam Shrivastava FRQs Review Ticket 2/7

### ISSUE THREAD

**Issue by devamshri** [ashwinbabu888/AP-CSA-T2#56]
### Analysis and Reflection (Partner: Eric Wang)
* **Overall**: 9/9 FRQ's Completed with 6/9 FRQ's with Input
* **Overall Comparison**:
> * He completed all of his FRQ's on a REPL, while I completed mine on my PBL site

* **Reflection**:
> * Overall, I think I had a really great time working on all of the FRQ's. I think that without the implementation of the FRQ's onto the PCL About-Us Pages, I wouldn't have gotten that great of a learning experience.
> * Weakness: I really struggled with ArrayLists and comparing them with Arrays. However, as I worked on the FRQ's, I learned that ArrayList's are modifiable by size, while regular arrays cannot be (static vs dynamic).
> * Strength: I think that recursion and iterations were something that came quite easily for me because I thought of them as how I would think of a recursive sequence in mathematics. May it be if-loops, for-loops, or while-loops, I believe that I can tell the difference between when to use each.

* FRQ 10:
> * Eric implements a method for testing within the Main method (basically using Main as a tester class). I utilize an input-based method to retrieve user-input and use it to carry out the functions.
> * In order to get the output, I utilize an ArrayList to store the Strings that are necessary for the Output. Eric's FRQ stores integers.
> * We both have similar methods for recursion (if statements).

* FRQ 9, Question 2:
> * We both have a method to test input-based mechanics.
> * I went above and beyond and utilized toString to get user input and get a wikipedia page.
> * We both have similar ways to define our methods.
> * I changed up the last part of the FRQ to be including of the wikipedia link rather than about Tusk size, but Eric continued with the tusk-size FRQ question. Nevertheless, we still have similar methods to complete both.

* FRQ 3:
> * Eric has input method for this one, while I don't. Rather than input, I utilize a tester method within a class that was specific for testing.
> * I utilize array's to help get the output of the testing method onto the frontend, while Eric doesn't need a frontend because he is using REPL.
> * We both have heavy emphasis on the Math function for the draw line. The Math method was one of the main things covered in Unit 3 as well.

### Relevant links
* [Runtime which has FRQ's](https://dnhslunchline.tk/individual/DShrivastava)
* [Wiki page link](https://github.com/ashwinbabu888/AP-CSA-T2/wiki/Devam-Shrivastava-FRQ-Walkthrough-Guide)
* [Video link](https://www.youtube.com/watch?v=JsqaFQRbwJ8)
* [My grading of Eric](https://github.com/yajatyadav/intellijs/issues/26)

**Comment by elw55555** [comment]
Test comment

**Comment by elw55555** [comment]
Test comment
