### ISSUE TITLE
Aman Jain FRQs Review Ticket 2/7

### ISSUE THREAD

**Issue by amanj31** [ashwinbabu888/AP-CSA-T2#57]
[Video Link](https://youtu.be/wIwWJ5ZqCkQ)
[Github Wiki](https://github.com/ashwinbabu888/AP-CSA-T2/wiki/Aman's-Key-Points-&-Learnings-from-FRQs)
[My grading of Akshay](https://github.com/nolanplatt/AP-CSA-T2/issues/41)

My FRQs are found [here](https://dnhslunchline.tk/individual/AJain), on my About page on our project site.

# Reflection and Comparison:
### Overall Strengths:
- I had many frqs with inputs. In particular, I had inputs for FRQ 8, which was a lot of work.
- My github wiki page has a lot of takeaways from the FRQs.
### Overall Weaknesses:
- My github wiki page could have code snippets to show better understanding.
### Comparison: Unit 5:
- Plus: Both of us have inputs for problems 1 and 2. These inputs function to update he website with a GET request (async)
- Minus: My input for the invite problem does not produce exactly the correct output (one of the variables results in null).
### Comparison: Unit 6: 
- Plus: I have inputs for FRQ 6 (both problems). This has an async function to update the website.
- Minus: My code displayed on my about page is minimal (only what is required to solve the Collegeboard problem). Akshay's code contains the whole class for the project.
### Comparison: Unit 8:
- Plus: I have inputs for this FRQ. This is a great plus because this FRQ needed a huge amount of user data to return results. This was a lot of work.
- Minus: Again, I do not show the whole class for the code. I could show the whole backend on my about page.

**Comment by Akshay-Rohatgi** [comment]
Aman has shown mastery of CollegeBoard topics through his completion of the unit FRQs. He has added outputs for nearly all of them and the corresponding code is shown for all. (9/9)

The video effectively and efficiently shows FRQ items on the about page. 

Wiki does not have code samples, does not show learning. Need specific takeaways. (-0.25)

9.75/10
